version = 0.1
[default.deploy.parameters]
stack_name = "playstudios-lambdas"
resolve_s3 = true
s3_prefix = "playstudios-lambdas"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
